Program        ::= { Statement } ;

Statement      ::= ExprStatement ;
ExprStatement  ::= Expression , ";" ;

Expression ::= StringLiteral | CallExpr | Identifier ;

CallExpr       ::= Identifier , "(" , [ ArgumentList ] , ")" ;
ArgumentList   ::= Expression , { "," , Expression } ;

Identifier     ::= ( Letter | "_" ) , { Letter | Digit | "_" } ;
StringLiteral  ::= '"' , { StringCharacter } , '"' ;

Letter         ::= "a" | ... | "z" | "A" | ... | "Z" ;
Digit          ::= "0" | ... | "9" ;

StringCharacter ::= ? any character except '"' and newline ? | EscapeSequence ;
EscapeSequence ::= "\" , ( '"' | "\" | "n" | "t" | "r" ) ;
